---
title: "gene project"
format: html
---


```{r}
library(bio3d)
library(pheatmap)
algn <- read.fasta("NPR3.aln-fasta")
```
 
```{r}
identity_matrix <- seqidentity(algn$ali)
```

```{r}
pheatmap(identity_matrix,
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         display_numbers = TRUE,
         fontsize_number = 8,
         fontsize_row = 10,
         fontsize_col = 10,
         main = "Sequence Identity Heatmap")
```


```{r}
identity_matrix
```


```{r}
rowMeans(identity_matrix)
```

```{r}
sort(rowMeans(identity_matrix), decreasing = TRUE)
```


```{r}
query.seq <- algn$ali[which(algn$id == "Mouse_NPR3"), ]
```

```{r}
query.seq <- paste(query.seq, collapse = "")
query.seq <- gsub("-", "", query.seq)
query.seq
```

```{r}
pdb.hits <- blast.pdb(query.seq)
```


```{r}
head(pdb.hits$hit.tbl)
```

```{r}
hits <- pdb.hits$hit.tbl
unique.hits <- hits[!duplicated(hits$pdb.id), ]
```

```{r}
top3 <- unique.hits[1:3, ]
top3
```
```{r}
anno <- pdb.annotate(top3$pdb.id)
anno 
```


```{r}
anno_match <- anno[match(top3$pdb.id, anno$structureId), ]

q8_table <- data.frame(
  PDB_ID = top3$pdb.id,
  Evalue = top3$evalue,
  Identity = top3$identity,
  Method = anno_match$experimentalTechnique,
  Resolution = anno_match$resolution,
  Source = anno_match$source
)

q8_table
```


```{r}
head(pdb.hits$hit.tbl)
```
```{r}
anno
```

